version: "3.8"
services:
  aggregate-db:
    container_name: aggregate-db
    image: mongo:6.0.5
    restart: always
    volumes:
      - mongodb_data:/data/aggregate_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - wms
  aggregate-ms:
    container_name: aggregate-ms
    depends_on:
      - aggregate-db
    build:
      context: .
    ports:
      - 3003:3000
    networks:
      - wms
    links:
      - aggregate-db
    restart: on-failure:3
    labels:
volumes:
  mongodb_data:
networks:
  wms:
    external: true
